# Data scraped from DCC Core Vocabulary highest frequency regular verbs.
# http://dcc.dickinson.edu/latin-vocabulary-list?field_search_lemma_value=&field_part_of_speech_value%5B%5D=Verb%3A+1st+Conjugation&field_part_of_speech_value%5B%5D=Verb%3A+2nd+Conjugation&field_part_of_speech_value%5B%5D=Verb%3A+3rd+Conjugation+-i%C5%8D&field_part_of_speech_value%5B%5D=Verb%3A+3rd+Conjugation+-%C5%8D&field_part_of_speech_value%5B%5D=Verb%3A+4th+Conjugation

# lemma / principal parts /, frequency rank (the lower the number, the more frequent)
VERB_LIST = [
    ['do', 'dare', 'dedi', 'datus'], # 28
    ['video', 'videre', 'vidi', 'visus'], # 31
    ['facio', 'facere', 'feci', 'factus'], # 32
    ['dico', 'dicere', 'dixi', 'dictus'], # 33
    ['habeo', 'habere', 'habui', 'habitus'], # 39
    ['venio', 'venire', 'veni', 'ventus'], # 63
    ['ago', 'agere', 'egi', 'actus'], # 69
    ['peto', 'petere', 'petivi', 'petitus'], # 83
    ['iubeo', 'iubere', 'iussi', 'iussus'], # 84
    ['vinco', 'vincere', 'vici', 'victus'], # 101
    ['pono', 'ponere', 'posui', 'positus'], # 102
    ['teneo', 'tenere', 'tenui', 'tentus'], # 106
    ['credo', 'credere', 'credidi', 'creditus'], # 109
    ['accipio', 'accipere', 'accepi', 'acceptus'], # 110
    ['quaero', 'quaerere', 'quaesivi', 'quaesitus'], # 113
    ['mitto', 'mittere', 'misi', 'missus'], # 114
    ['capio', 'capere', 'cepi', 'captus'], # 131
    ['duco', 'ducere', 'duxi', 'ductus'], # 133
    ['relinquo', 'relinquere', 'reliqui', 'relictus'], # 144
    ['timeo', 'timere', 'timui'], # 153
    ['debeo', 'debere', 'debui', 'debitus'], # 155
    ['vivo', 'vivere', 'vixi', 'victus'], # 156
    ['voco', 'vocare', 'vocavi', 'vocatus'], # 158
    ['paro', 'parare', 'paravi', 'paratus'], # 160
    ['audio', 'audire', 'audivi/audii', 'auditus'], # 165
    ['puto', 'putare', 'putavi', 'putatus'], # 166
    ['sto', 'stare', 'steti', 'status'], # 168
    ['scio', 'scire', 'scivi/scii', 'scitus'], # 172
    ['reddo', 'reddere', 'reddidi', 'redditus'], # 174
    ['fugio', 'fugere', 'fugi', 'fugitus'], # 177
    ['moveo', 'movere', 'movi', 'motus'], # 192
    ['cado', 'cadere', 'cecidi', 'casus'], # 210
    ['traho', 'trahere', 'traxi', 'tractus'], # 213
    ['amo', 'amare', 'amavi', 'amatus'], # 219
    ['iaceo', 'iacere', 'iacui', 'iacitus'], # 228
    ['gero', 'gerere', 'gessi', 'gestus'], # 237
    ['premo', 'premere', 'pressi', 'pressus'], # 240
    ['soleo', 'solere', 'solui', 'solitus'], # 246
    ['cogo', 'cogere', 'coegi', 'coactus'], # 250
    ['audeo', 'audere', 'ausus sum', ], # 270
    ['rapio', 'rapere', 'rapui', 'raptus'], # 273
    ['placeo', 'placere', 'placui', 'placitus'], # 287
    ['verto', 'vertere', 'verti', 'versus'], # 288
    ['servo', 'servare', 'servavi', 'servatus'], # 289
    ['nego', 'negare', 'negavi', 'negatus'], # 294
    ['trado', 'tradere', 'tradidi', 'traditus'], # 297
    ['sentio', 'sentire', 'sensi', 'sensus'], # 302
    ['cedo', 'cedere', 'cessi', 'cessus'], # 304
    ['muto', 'mutare', 'mutavi', 'mutatus'], # 315
    ['invenio', 'invenire', 'inveni', 'inventus'], # 316
    ['recipio', 'recipere', 'recepi', 'receptus'], # 319
    ['solvo', 'solvere', 'solvi', 'solutus'], # 325
    ['colo', 'colere', 'colui', 'cultus'], # 333
    ['cognosco', 'cognoscere', 'cognovi', 'cognitus'], # 339
    ['frango', 'frangere', 'fregi', 'fractus'], # 345
    ['nosco', 'noscere', 'novi', 'notus'], # 347
    ['eripio', 'eripere', 'eripui', 'ereptus'], # 349
    ['maneo', 'manere', 'mansi', 'mansus'], # 357
    ['taceo', 'tacere', 'tacui', 'tacitus'], # 369
    ['ostendo', 'ostendere', 'ostendi', 'ostentus'], # 371
    ['tego', 'tegere', 'texi', 'tectus'], # 376
    ['cano', 'canere', 'cecini', 'cantus'], # 389
    ['iuvo', 'iuvare', 'iuvi', 'iutus'], # 390
    ['claudo', 'claudere', 'clausi', 'clausus'], # 392
    ['doceo', 'docere', 'docui', 'doctus'], # 393
    ['excipio', 'excipere', 'excepi', 'exceptus'], # 394
    ['erro', 'errare', 'erravi', 'erratus'], # 402
    ['gaudeo', 'gaudere', 'gavisus sum'], # 407
    ['pervenio', 'pervenire', 'perveni', 'perventus'], # 409
    ['incipio', 'incipere', 'incepi', 'inceptus'], # 411
    ['parco', 'parcere', 'peperci', 'parsus'], # 412
    ['opto', 'optare', 'optavi', 'optatus'], # 417
    ['lego', 'legere', 'legi', 'lectus'], # 419
    ['praesto', 'praestare', 'praestiti', 'praestitus'], # 423
    ['misceo', 'miscere', 'miscui', 'mixtus'], # 425
    ['metuo', 'metuere', 'metui', ], # 429
    ['tempto', 'temptare', 'temptavi', 'temptatus'], # 430
    ['addo', 'addere', 'addidi', 'additus'], # 433
    ['laudo', 'laudare', 'laudavi', 'laudatus'], # 435
    ['impono', 'imponere', 'imposui', 'impositus'], # 437
    ['cupio', 'cupere', 'cupivi', 'cupitus'], # 441
    ['exspecto', 'exspectare', 'exspectavi', 'exspectatus'], # 442
    ['compono', 'componere', 'composui', 'compositus'], # 443
    ['sumo', 'sumere', 'sumpsi', 'sumptus'], # 454
    ['fleo', 'flere', 'flevi', 'fletus'], # 457
    ['disco', 'discere', 'didici', ], # 465
    ['occupo', 'occupare', 'occupavi', 'occupatus'], # 472
    ['specto', 'spectare', 'spectavi', 'spectatus'], # 473
    ['rumpo', 'rumpere', 'rupi', 'ruptus'], # 480
    ['aspicio', 'aspicere', 'aspexi', 'aspectus'], # 483
    ['amitto', 'amittere', 'amisi', 'amissus'], # 486
    ['posco', 'poscere', 'poposci', ], # 487
    ['perdo', 'perdere', 'perdidi', 'perditus'], # 488
    ['contingo', 'contingere', 'contigi', 'contactus'], # 494
    ['exigo', 'exigere', 'exegi', 'exactus'], # 500
    ['fallo', 'fallere', 'fefelli', 'falsus'], # 503
    ['sedeo', 'sedere', 'sedi', 'sessus'], # 506
    ['noceo', 'nocere', 'nocui', 'nocitus'], # 509
    ['intellego', 'intellegere', 'intellexi', 'intellectus'], # 512
    ['iungo', 'iungere', 'iunxi', 'iunctus'], # 513
    ['cogito', 'cogitare', 'cogitavi', 'cogitatus'], # 515
    ['dubito', 'dubitare', 'dubitavi', 'dubitatus'], # 521
    ['fundo', 'fundere', 'fudi', 'fusus'], # 523
    ['nescio', 'nescire', 'nescivi/nescii', 'nescitus'], # 525
    ['tendo', 'tendere', 'tetendi', 'tentus'], # 529
    ['spargo', 'spargere', 'sparsi', 'sparsus'], # 532
    ['tango', 'tangere', 'tetigi', 'tactus'], # 534
    ['respondeo', 'respondere', 'respondi', 'responsus'], # 535
    ['propero', 'properare', 'properavi', 'properatus'], # 537
    ['valeo', 'valere', 'valui', 'valitus'], # 539
    ['condo', 'condere', 'condidi', 'conditus'], # 540
    ['desero', 'deserere', 'deserui', 'desertus'], # 544
    ['pateo', 'patere', 'patui', ], # 550
    ['rogo', 'rogare', 'rogavi', 'rogatus'], # 551
    ['rego', 'regere', 'rexi', 'rectus'], # 554
    ['curro', 'currere', 'cucurri', 'cursus'], # 562
    ['pello', 'pellere', 'pepuli', 'pulsus'], # 563
    ['iudico', 'iudicare', 'iudicavi', 'iudicatus'], # 565
    ['scribo', 'scribere', 'scripsi', 'scriptus'], # 568
    ['surgo', 'surgere', 'surrexi', 'surrectus'], # 570
    ['careo', 'carere', 'carui', 'caritus'], # 572
    ['efficio', 'efficere', 'effeci', 'effectus'], # 573
    ['exerceo', 'exercere', 'exercui', 'exercitus'], # 576
    ['agito', 'agitare', 'agitavi', 'agitatus'], # 578
    ['sono', 'sonare', 'sonui', 'sonitus'], # 583
    ['praebeo', 'praebere', 'praebui', 'praebitus'], # 584
    ['impero', 'imperare', 'imperavi', 'imperatus'], # 602
    ['prohibeo', 'prohibere', 'prohibui', 'prohibitus'], # 604
    ['dono', 'donare', 'donavi', 'donatus'], # 606
    ['committo', 'committere', 'commisi', 'commissus'], # 608
    ['cresco', 'crescere', 'crevi', 'cretus'], # 609
    ['caedo', 'caedere', 'cecidi', 'caesus'], # 612
    ['existimo', 'existimare', 'existimavi', 'existimatus'], # 613
    ['accedo', 'accedere', 'accessi', 'accessus'], # 614
    ['contemno', 'contemnere', 'contempsi', 'contemptus'], # 615
    ['ardeo', 'ardere', 'arsi', 'arsus'], # 618
    ['desino', 'desinere', 'desii', 'desitus'], # 624
    ['divido', 'dividere', 'divisi', 'divisus'], # 628
    ['veho', 'vehere', 'vexi', 'vectus'], # 632
    ['retineo', 'retinere', 'retinui', 'retentus'], # 647
    ['spero', 'sperare', 'speravi', 'speratus'], # 648
    ['repeto', 'repetere', 'repetivi', 'repetitus'], # 651
    ['constituo', 'constituere', 'constitui', 'constitutus'], # 652
    ['defendo', 'defendere', 'defendi', 'defensus'], # 653
    ['cerno', 'cernere', 'crevi', 'cretus'], # 655
    ['deduco', 'deducere', 'deduxi', 'deductus'], # 661
    ['concedo', 'concedere', 'concessi', 'concessus'], # 663
    ['veto', 'vetare', 'vetui', 'vetitus'], # 665
    ['gigno', 'gignere', 'genui', 'genitus'], # 667
    ['supero', 'superare', 'superavi', 'superatus'], # 668
    ['impleo', 'implere', 'implevi', 'impletus'], # 671
    ['deficio', 'deficere', 'defeci', 'defectus'], # 676
    ['occurro', 'occurrere', 'occucurri', 'occursus'], # 677
    ['statuo', 'statuere', 'statui', 'statutus'], # 678
    ['edo', 'edere', 'edidi', 'editus'], # 688
    ['lateo', 'latere', 'latui', ], # 695
    ['convenio', 'convenire', 'conveni', 'conventus'], # 698
    ['interficio', 'interficere', 'interfeci', 'interfectus'], # 699
    ['appello', 'appellare', 'appelavi', 'appellatus'], # 700
    ['permitto', 'permittere', 'permisi', 'permissus'], # 702
    ['terreo', 'terrere', 'terrui', 'territus'], # 705
    ['pugno', 'pugnare', 'pugnavi', 'pugnatus'], # 708
    ['augeo', 'augere', 'auxi', 'auctus'], # 709
    ['moneo', 'monere', 'monui', 'monitus'], # 711
    ['sino', 'sinere', 'sivi', 'situs'], # 717
    ['effundo', 'effundere', 'effudi', 'effusus'], # 719
    ['promitto', 'promittere', 'promisi', 'promissus'], # 720
    ['fingo', 'fingere', 'finxi', 'fictus'], # 721
    ['respicio', 'respicere', 'respexi', 'respectus'], # 722
    ['vaco', 'vacare', 'vacavi', 'vacatus'], # 724
    ['discedo', 'discedere', 'discessi', 'discessus'], # 726
    ['consto', 'constare', 'constiti', 'constatus'], # 731
    ['curo', 'curare', 'curavi', 'curatus'], # 743
    ['procedo', 'procedere', 'processi', 'processus'], # 746
    ['damno', 'damnare', 'damnavi', 'damnatus'], # 751
    ['oro', 'orare', 'oravi', 'oratus'], # 755
    ['consulo', 'consulere', 'consului', 'consultus'], # 757
    ['sustineo', 'sustinere', 'sustinui', 'sustentus'], # 762
    ['reperio', 'reperire', 'repperi', 'repertus'], # 765
    ['intro', 'intrare', 'intravi', 'intratus'], # 766
    ['fluo', 'fluere', 'fluxi', 'fluxus'], # 772
    ['dimitto', 'dimittere', 'dimisi', 'dimissus'], # 777
    ['consisto', 'consistere', 'constiti', 'constitus'], # 780
    ['laedo', 'laedere', 'laesi', 'laesus'], # 783
    ['probo', 'probare', 'probavi', 'probatus'], # 784
    ['doleo', 'dolere', 'dolui', 'dolitus'], # 785
    ['pecco', 'peccare', 'peccavi', 'peccatus'], # 792
    ['accido', 'accidere', 'accidi', ], # 799
    ['decerno', 'decernere', 'decrevi', 'decretus'], # 800
    ['occido', 'occidere', 'occidi', 'occisus'], # 801
    ['descendo', 'descendere', 'descendi', 'descensus'], # 802
    ['contineo', 'continere', 'continui', 'contentus'], # 804
    ['revoco', 'revocare', 'revocavi', 'revocatus'], # 813
    ['cingo', 'cingere', 'cinxi', 'cinctus'], # 814
    ['alo', 'alere', 'alui', 'alitus'], # 817
    ['colligo', 'colligere', 'collegi', 'collectus'], # 820
    ['pergo', 'pergere', 'perrexi', 'perrectus'], # 821
    ['recedo', 'recedere', 'recessi', 'recessus'], # 826
    ['pario', 'parere', 'peperi', 'partus'], # 829
    ['appareo', 'apparere', 'apparui', 'apparitus'], # 830
    ['converto', 'convertere', 'converti', 'conversus'], # 834
    ['aperio', 'aperire', 'aperui', 'apertus'], # 837
    ['pareo', 'parere', 'parui', 'paritus'], # 847
    ['mereo', 'merere', 'merui', 'meritus'], # 852
    ['porto', 'portare', 'portavi', 'portatus'], # 853
    ['certo', 'certare', 'certavi', 'certatus'], # 864
    ['pertineo', 'pertinere', 'pertinui', ], # 866
    ['turbo', 'turbare', 'turbavi', 'turbatus'], # 868
    ['consumo', 'consumere', 'consumpsi', 'consumptus'], # 869
    ['corrumpo', 'corrumpere', 'corrupi', 'corruptus'], # 870
    ['incido', 'incidere', 'incidi', 'incasus'], # 871
    ['rideo', 'ridere', 'risi', 'risus'], # 874
    ['vito', 'vitare', 'vitavi', 'vitatus'], # 881
    ['servio', 'servire', 'servivi/servii', 'servitus'], # 883
    ['adduco', 'adducere', 'adduxi', 'adductus'], # 886
    ['comparo', 'comparare', 'comparavi', 'comparatus'], # 890
    ['desidero', 'desiderare', 'desideravi', 'desideratus'], # 892
    ['celebro', 'celebrare', 'celebravi', 'celebratus'], # 893
    ['conficio', 'conficere', 'confeci', 'confectus'], # 894
    ['intendo', 'intendere', 'intendi', 'intentus'], # 895
    ['iuro', 'iurare', 'iuravi', 'iuratus'], # 896
    ['iacio', 'iacere', 'ieci', 'iactus'], # 899
    ['laboro', 'laborare', 'laboravi', 'laboratus'], # 900
    ['narro', 'narrare', 'narravi', 'narratus'], # 910
    ['censeo', 'censere', 'censui', 'census'], # 928
    ['prodo', 'prodere', 'prodidi', 'proditus'], # 929
    ['propono', 'proponere', 'proposui', 'propositus'], # 930
    ['instituo', 'instituere', 'institui', 'institutus'], # 931
    ['educo', 'educere', 'eduxi', 'eductus'], # 935
    ['suscipio', 'suscipere', 'suscepi', 'susceptus'], # 937
    ['caveo', 'cavere', 'cavi', 'cautus'], # 941
    ['eligo', 'eligere', 'elegi', 'electus'], # 942
    ['praecipio', 'praecipere', 'praecepi', 'praeceptus'], # 945
    ['interrogo', 'interrogare', 'interrogavi', 'interrogatus'], # 953
    ['fugo', 'fugare', 'fugavi', 'fugatus'], # 957
    ['afficio', 'afficere', 'affeci', 'affectus'], # 958
    ['adhibeo', 'adhibere', 'adhibui', 'adhibitus'], # 959
    ['quiesco', 'quiescere', 'quievi', 'quietus'], # 969
    ['diligo', 'diligere', 'dilexi', 'dilectus'], # 973
    ['dormio', 'dormire', 'dormivi/dormii', 'dormitus'], # 975
    ['creo', 'creare', 'creavi', 'creatus'], # 978
    ['indico', 'indicare', 'indicavi', 'indicatus'], # 980
    ['adverto', 'advertere', 'adverti', 'adversus'], # 986
    ['advenio', 'advenire', 'adveni', 'adventus'], # 987
    ['pendo', 'pendere', 'pependi', 'pensus'], # 988
    ['studeo', 'studere', 'studui', ], # 989
    ['ascendo', 'ascendere', 'ascendi', 'ascensus'], # 990
    ['reverto', 'revertere', 'reverti', 'reversus'], # 995
    ['edico', 'edicere', 'edixi', 'edictus'], # 996
]
